// Package winget parses the small, security-relevant subset of a WinGet
// installer manifest used by Community+ catalog imports.
package winget

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/url"
	"strings"

	"gopkg.in/yaml.v3"
)

type Manifest struct {
	PackageIdentifier string
	PackageVersion    string
	InstallerType     string
	InstallerURL      string
	InstallerSHA256   string
	ProductCode       string
}

type document struct {
	PackageIdentifier string `yaml:"PackageIdentifier"`
	PackageVersion    string `yaml:"PackageVersion"`
	Installers        []struct {
		Architecture           string `yaml:"Architecture"`
		InstallerType          string `yaml:"InstallerType"`
		InstallerURL           string `yaml:"InstallerUrl"`
		InstallerSHA256        string `yaml:"InstallerSha256"`
		ProductCode            string `yaml:"ProductCode"`
		AppsAndFeaturesEntries []struct {
			ProductCode string `yaml:"ProductCode"`
		} `yaml:"AppsAndFeaturesEntries"`
	} `yaml:"Installers"`
}

// Parse selects an x64 installer, falling back to a neutral installer. Only
// MSI/MSIX types are accepted: arbitrary EXE command lines require explicit
// review and must not be generated by a catalog import.
func Parse(data []byte) (Manifest, error) {
	var doc document
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return Manifest{}, fmt.Errorf("parse WinGet manifest: %w", err)
	}
	if doc.PackageIdentifier == "" || doc.PackageVersion == "" {
		return Manifest{}, fmt.Errorf("WinGet manifest requires PackageIdentifier and PackageVersion")
	}
	var selected *struct {
		Architecture           string `yaml:"Architecture"`
		InstallerType          string `yaml:"InstallerType"`
		InstallerURL           string `yaml:"InstallerUrl"`
		InstallerSHA256        string `yaml:"InstallerSha256"`
		ProductCode            string `yaml:"ProductCode"`
		AppsAndFeaturesEntries []struct {
			ProductCode string `yaml:"ProductCode"`
		} `yaml:"AppsAndFeaturesEntries"`
	}
	for i := range doc.Installers {
		candidate := &doc.Installers[i]
		if strings.EqualFold(candidate.Architecture, "x64") {
			selected = candidate
			break
		}
		if selected == nil && strings.EqualFold(candidate.Architecture, "neutral") {
			selected = candidate
		}
	}
	if selected == nil {
		return Manifest{}, fmt.Errorf("WinGet package %q has no x64 or neutral installer", doc.PackageIdentifier)
	}
	typ := strings.ToLower(selected.InstallerType)
	if typ != "msi" && typ != "msix" && typ != "msixbundle" {
		return Manifest{}, fmt.Errorf("WinGet package %q has unsupported installer type %q", doc.PackageIdentifier, typ)
	}
	u, err := url.ParseRequestURI(selected.InstallerURL)
	if err != nil || u.Scheme != "https" || u.Host == "" {
		return Manifest{}, fmt.Errorf("WinGet package %q requires HTTPS InstallerUrl", doc.PackageIdentifier)
	}
	hash, err := hex.DecodeString(selected.InstallerSHA256)
	if err != nil || len(hash) != sha256.Size {
		return Manifest{}, fmt.Errorf("WinGet package %q requires a SHA-256 InstallerSha256", doc.PackageIdentifier)
	}
	productCode := selected.ProductCode
	if productCode == "" && len(selected.AppsAndFeaturesEntries) == 1 {
		productCode = selected.AppsAndFeaturesEntries[0].ProductCode
	}
	return Manifest{PackageIdentifier: doc.PackageIdentifier, PackageVersion: doc.PackageVersion, InstallerType: typ, InstallerURL: selected.InstallerURL, InstallerSHA256: strings.ToLower(selected.InstallerSHA256), ProductCode: productCode}, nil
}
